name: "Github Action Test"

on:
  push:

jobs: 
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: pip install python-telegram-bot
      - name: Run python script
        run: python main.py
        env:
          TOKEN: ${{secrets.TOKEN}}
